// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideBar: typeof import('./src/components/Layout/components/AsideBar/index.vue')['default']
    Assist: typeof import('./src/components/Layout/components/Assist/index.vue')['default']
    BtnGroup: typeof import('./src/components/Layout/components/Assist/components/btnGroup/index.vue')['default']
    Contextmenu: typeof import('./src/components/Contextmenu/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/Layout/components/Header/index.vue')['default']
    IconGather: typeof import('./src/components/Layout/components/Header/components/IconGather/index.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MenuItem: typeof import('./src/components/Layout/components/AsideBar/components/NavMenu/MenuItem/index.vue')['default']
    NavMenu: typeof import('./src/components/Layout/components/AsideBar/components/NavMenu/index.vue')['default']
    RouteBreadcrumb: typeof import('./src/components/Layout/components/Header/components/RouteBreadcrumb/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPane: typeof import('./src/components/Layout/components/SettingPane/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SystemTitle: typeof import('./src/components/Layout/components/AsideBar/components/SystemTitle/index.vue')['default']
    Tags: typeof import('./src/components/Layout/components/Assist/components/tags/index.vue')['default']
    UserInfo: typeof import('./src/components/Layout/components/Header/components/userInfo/index.vue')['default']
  }
}
